# Generated by Django 5.2.10 on 2026-01-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
