# Generated by Django 5.2.10 on 2026-01-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_urldata_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='urldata',
            name='count',
        ),
    ]
